sudo: false

language: php

php:
  - 7.0
  - 7.1
  - nightly

services:
 - redis-server

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
  # --ignore-platform-reqs, because https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2722
  - composer update -n --prefer-dist --ignore-platform-reqs
  - composer require satooshi/php-coveralls dev-master --ignore-platform-reqs

script:
  - find -name "*.php" -not -path "./vendor/*" -print0 | xargs -n 1 -0 php -l
  - phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - php vendor/bin/coveralls -v

cache:
  directories:
    - $HOME/.composer/cache/files
